### ISSUE TITLE
env-paths breaks when logged in as root

### ISSUE THREAD

**Issue by camwest** [greenkeeperio/rc#6]
Hey there, this feature (https://github.com/greenkeeperio/rc/commit/8384cb11bf9d222e67fd2614ff30efb84f041213) caused a bug for us. We run greenkeeper inside of a Docker container running as root. env-paths doesn't work when run as root on Linux. It throws an error since it does string splitting on the homedir but the root homedir doesn't work correctly. https://github.com/sindresorhus/env-paths/blob/dfddd546f95e4606b7373e5091ad0b2db24e99fc/index.js#L35 returns undefined which causes node to throw an exception.

**Comment by finnp** [comment]
Hey, thanks for reporting this. Could you create an issue on `env-paths` about this as well? They should never throw an exception and maybe default to a sane alternative.

Best, Finn

**Comment by Siilwyn** [comment]
This is fixed in the latest version of `env-paths`.

**Comment by finnp** [comment]
@Siilwyn Awesome! Thank you!
